const SIDEBAR_COOKIE_NAME = "sidebar_state";
const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;
const SIDEBAR_WIDTH = "20rem";
const SIDEBAR_WIDTH_MOBILE = "20rem";
const SIDEBAR_WIDTH_ICON = "5rem";
const SIDEBAR_KEYBOARD_SHORTCUT = "b";

export const SIDEBAR_CONFIG = {
  COOKIE_NAME: SIDEBAR_COOKIE_NAME,
  COOKIE_MAX_AGE: SIDEBAR_COOKIE_MAX_AGE,
  WIDTH: SIDEBAR_WIDTH,
  WIDTH_MOBILE: SIDEBAR_WIDTH_MOBILE,
  WIDTH_ICON: SIDEBAR_WIDTH_ICON,
  KEYBOARD_SHORTCUT: SIDEBAR_KEYBOARD_SHORTCUT,
};
